services:
  todo-frontend:
    image: todo-front-dev
    ports:
      - 3000:3000
    container_name: todo-front-dev-nginx
    volumes:
      - ./todo-frontend:/usr/src/app

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-full
    depends_on:
      - todo-frontend
