version: '3.8'

services:
  todo-frontend:
    image: todo-front-dev
    ports:
      - 3000:3000
    container_name: todo-front-dev-nginx
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      NODE_ENV: 'development'

  todo-backend:
    image: todo-backend-dev
    ports:
      - 3001:3001
    container_name: todo-back-dev-nginx
    environment:
      PORT: 3001
      NODE_ENV: 'development'
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database

    volumes:
      - ./todo-backend:/usr/src/app

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-full
    depends_on:
      - todo-frontend
      - todo-backend

volumes:
  mongo_data:
